cookietemple_version: '1.4.0 # <<COOKIETEMPLE_NO_BUMP>>'
domain: cli
language: python
project_slug: pertpy
project_slug_no_hyphen: pertpy
template_version: '2.1.0 # <<COOKIETEMPLE_NO_BUMP>>'
template_handle: cli-python
github_username: theislab
creator_github_username: zethson
is_github_repo: true
is_repo_private: false
is_github_orga: true
github_orga: theislab
full_name: Lukas Heumos
email: lukas.heumos@posteo.net
project_name: pertpy
project_short_description: Perturbation Analysis in the Scanpy ecosystem.
version: 0.4.0
license: MIT
