version: 2

sphinx:
    configuration: docs/conf.py

formats: []

build:
    os: ubuntu-22.04
    tools:
        python: "3.10"
    jobs:
        post_install:
            - pip install .
            - pip install -r docs/requirements.txt

submodules:
    include: all
