version: 2
build:
    os: ubuntu-22.04
    tools:
        python: "3.11"
    jobs:
        pre_build:
            - python -c "import pertpy"
            - pip freeze
sphinx:
    configuration: docs/conf.py
    fail_on_warning: false
python:
    install:
        - method: pip
          path: .
          extra_requirements:
              - doc
              - coda

submodules:
    include: all
