name: Run Notebooks

on:
    - push
    - pull_request_target

jobs:
    run:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                notebook: [
                        "docs/tutorials/notebooks/mixscape.ipynb",
                        # "docs/tutorials/notebooks/augurpy.ipynb",
                    ]
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: "true"
                  token: "${{ secrets.CT_SYNC_TOKEN }}"
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install Poetry
              run: |
                  pip install poetry
                  poetry --version

            - name: Install package
              run: poetry install

            - name: Install nbconvert ipykernel
              run: poetry add nbconvert ipykernel

            - name: Run ${{ matrix.notebook }} Notebook
              run: poetry run jupyter nbconvert --to notebook --execute ${{ matrix.notebook }}
